# 3. Numpy

### (1) 넘파이를 쓰면 무엇이 좋은가? 

**[예1]** Numpy를 활용한 벡터연산

`욕심`: `(1,2,3)+(2,3,4)=(3,5,7)`를 계산하고 싶다. 

(실패)

일반 리스트 경우

In [5]:
a=[1,2,3]
b=[2,3,4]
a+b

[1, 2, 3, 2, 3, 4]

(성공)

In [6]:
[a[0]+b[0],a[1]+b[1],a[2]+b[2]]

[3, 5, 7]

(성공2)

In [7]:
a[0]+b[0],a[1]+b[1],a[2]+b[2]

(3, 5, 7)

In [8]:
temp_ = a[0]+b[0],a[1]+b[1],a[2]+b[2]

In [9]:
temp_

(3, 5, 7)

In [10]:
list(temp_)

[3, 5, 7]

(원소가 많을경우를 대비- 실패)

In [25]:
c=[]
for i in [0,1,2]:
    c[i]=a[i]+b[i]

IndexError: list assignment index out of range

In [12]:
c=[]
c[0]=1

IndexError: list assignment index out of range

In [20]:
c=[]
c=c+[1]

In [19]:
c

[1, 2]

(성공)

In [27]:
c=[]
for i in [0,1,2]:
    c=c+[a[i]+b[i]]

In [34]:
c

[3, 5, 7]

(성공)

In [28]:
a=[1,2,3]
b=[2,3,4]
c=[a[i]+b[i] for i in [0,1,2]]

In [29]:
c

[3, 5, 7]

(넘파이) - 제일 편한 코드

In [31]:
import numpy as np 

In [38]:
a=np.array((1,2,3))
b=np.array([2,3,4])

In [39]:
a+b

array([3, 5, 7])

#### [$\ast$] 넘파이의 호환성

`list` - `tuple` - `np.array`사이에는 호환성이 좋음 

In [40]:
a=[1,2,3]

In [41]:
list(np.array(tuple(a)))

[1, 2, 3]

#### [$\ast$] 넘파이의 정체

`numpy`의 정체는 뭔가 특별한것이 아니었고, 그냥 폴더이름이었음. 

In [42]:
import math

`math`의 정체는 파일 

`/home/cgb2/anaconda3/envs/py38r40/lib/python3.8/lib-dynload` 에 있는 파일




---

**[예2]** 넘파이(numpy)를 왜 써야하는가? (2) 

넘파이를 사용하면 벡터연산과 행렬연산을 쉽게 할 수 있다. 

예를들어 아래와 같은 문제가 있다고 하자. 

$\begin{cases}
w+2x+3y+4z=1 \\
2w+2x+y=9 \\
x-y=4 \\
3w+x-y+3y=7
\end{cases}$

매트릭스 형태로 위의 식을 표현하면 아래와 같다. 

$\begin{bmatrix}
1 & 2 & 3 & 4 \\ 
2 & 2 & 1 & 0 \\
0 & 1 &-1 & 0 \\
3 & 1 &-1 & 3 
\end{bmatrix}
\begin{bmatrix}
w \\ x \\ y \\z 
\end{bmatrix}=\begin{bmatrix}
1 \\ 9 \\ 4 \\7 
\end{bmatrix}$


양변에 $\begin{bmatrix}
1 & 2 & 3 & 4 \\ 
2 & 2 & 1 & 0 \\
0 & 1 &-1 & 0 \\
3 & 1 &-1 & 3 
\end{bmatrix}$의 역행렬을 취하면 



$\begin{bmatrix}
w \\ x \\ y \\z 
\end{bmatrix}=\begin{bmatrix}
1 & 2 & 3 & 4 \\ 
2 & 2 & 1 & 0 \\
0 & 1 &-1 & 0 \\
3 & 1 &-1 & 3 
\end{bmatrix}^{-1}\begin{bmatrix}
1 \\ 9 \\ 4 \\7 
\end{bmatrix}$

In [1]:
A=[[1,2,3,4],[2,2,1,0],[0,1,-1,0],[3,1,-1,3]]

In [44]:
A

[[1, 2, 3, 4], [2, 2, 1, 0], [0, 1, -1, 0], [3, 1, -1, 3]]

list로 선언된 A를 np.matrix로 변환

In [45]:
Amat=np.matrix(A)

In [46]:
Amat

matrix([[ 1,  2,  3,  4],
        [ 2,  2,  1,  0],
        [ 0,  1, -1,  0],
        [ 3,  1, -1,  3]])

변환된 매트릭스의 역행렬을 구함.

In [47]:
Amat.I

matrix([[-0.15789474,  0.26315789, -0.42105263,  0.21052632],
        [ 0.10526316,  0.15789474,  0.61403509, -0.14035088],
        [ 0.10526316,  0.15789474, -0.38596491, -0.14035088],
        [ 0.15789474, -0.26315789,  0.0877193 ,  0.12280702]])

In [48]:
b=[1,9,4,7]

In [49]:
bvec=np.matrix(b)

In [50]:
bvec

matrix([[1, 9, 4, 7]])

`bvec`은 $1\times 4$ 매트릭스가 된 셈. 

그런데 우리가 원한것은 $4\times 1$ 매트릭스였음. 

In [51]:
bvec=bvec.T
bvec

matrix([[1],
        [9],
        [4],
        [7]])

In [52]:
Amat.I*bvec

matrix([[ 2.],
        [ 3.],
        [-1.],
        [-1.]])

$\begin{bmatrix}
w \\ x \\ y \\z 
\end{bmatrix}=\begin{bmatrix}
1 & 2 & 3 & 4 \\ 
2 & 2 & 1 & 0 \\
0 & 1 &-1 & 0 \\
3 & 1 &-1 & 3 
\end{bmatrix}^{-1}\begin{bmatrix}
1 \\ 9 \\ 4 \\7 
\end{bmatrix}=\begin{bmatrix}
2 \\ 3 \\ -1 \\-1 
\end{bmatrix}$

따라서 $w=2, x=3, y=-1,z=-1$가 된다. 

(확인)

$\begin{cases}
w+2x+3y+4z=1 \\
2w+2x+y=9 \\
x-y=4 \\
3w+x-y+3y=7
\end{cases}$

에 넣어보자. 

---

(숙제) 

$\begin{cases}
x+y=2 \\
y+z=2 \\
z+x=2
\end{cases}$

를 파이썬을 활용하여 풀어라.

In [53]:
A=[[1,1,0],[0,1,1],[1,0,1]]

In [54]:
Amat=np.matrix(A)
Amat

matrix([[1, 1, 0],
        [0, 1, 1],
        [1, 0, 1]])

In [55]:
bvec=np.matrix([2,2,2]).T
bvec

matrix([[2],
        [2],
        [2]])

---

### (2) 배열 vs 행렬 (`np.array` vs `np.matrix`)

아래의 문제를 다시 살펴보자. 

$\begin{bmatrix}
1 & 2 & 3 & 4 \\ 
2 & 2 & 1 & 0 \\
0 & 1 &-1 & 0 \\
3 & 1 &-1 & 3 
\end{bmatrix}
\begin{bmatrix}
w \\ x \\ y \\z 
\end{bmatrix}=\begin{bmatrix}
1 \\ 9 \\ 4 \\7 
\end{bmatrix}$


$(w,x,y,z)$를 풀기위해서는 

In [67]:
A=[[1,2,3,4],[2,2,1,0],[0,1,-1,0],[3,1,-1,3]]
b=[1,9,4,7]
Amat=np.matrix(A)
bvec=np.matrix(b).T
Amat.I * bvec

matrix([[ 2.],
        [ 3.],
        [-1.],
        [-1.]])

그런데 아래처럼 구해도 괜찮다. 

@는 array의 *는 그저 곱셈이 되니 행렬의 곱을 할 수 있게 만든 기호

matrix 자료형에서는 *이 곧 행렬의 곱이 된다. 

In [32]:
A=[[1,2,3,4],[2,2,1,0],[0,1,-1,0],[3,1,-1,3]]
b=[1,9,4,7]
Aarr=np.array(A)
barr=np.array(b)
np.linalg.inv(Aarr) @barr 

array([ 2.,  3., -1., -1.])

`np.linalg.inv()`가 통째로 역행렬을 구하는 함수다.

In [69]:
from numpy.linalg import inv
A=[[1,2,3,4],[2,2,1,0],[0,1,-1,0],[3,1,-1,3]]
b=[1,9,4,7]
Aarr=np.array(A)
barr=np.array(b)
inv(Aarr) @ barr 

array([ 2.,  3., -1., -1.])

왜 `np.matrix`를 썼는가? 
- 행렬곱 
- 역행렬계산

`np.matrix`가 진짜 편한가? (저는 편해요..)

**[불만1]** 1차원자료형에 `np.matrix`를 쓰는게 이상하다. 

- `np.array`: 1차원 자료에 특화된 느낌
- `np.matrix`: 2차원 자료에 특화된 느낌

In [70]:
barr.shape

(4,)

In [71]:
bvec.shape

(4, 1)

이럴꺼면 굳이 1차원 자료형인 `np.array`를 왜 만드는지? 

In [38]:
np.matrix([1,2,3])+np.matrix([4,5,6])

matrix([[5, 7, 9]])

**[불만2]** 3차원 자료가 있다면 어떻게 표현할래?

In [40]:
B=[[[1,2],[2,3],[3,4]],[[3,2],[2,2],[4,1]]]

In [41]:
B[0]

[[1, 2], [2, 3], [3, 4]]

In [42]:
B[0][1]

[2, 3]

In [43]:
B[0][1][0]

2

In [44]:
np.array(B)+100

array([[[101, 102],
        [102, 103],
        [103, 104]],

       [[103, 102],
        [102, 102],
        [104, 101]]])

In [45]:
np.matrix(B)+100

ValueError: matrix must be 2-dimensional

**[불만3]** `np.array`, `np.matrix`가 같이 있으면 혼란이 생긴다. col-vector, row-vector를 굳이 구분하고 싶지 않다.   

내적: $b=\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}$라는 벡터가 있다고 하자.

벡터의 크기의 제곱: $1^2+2^2+3^2$

벡터의 크기: $\sqrt{1^2+2^2+3^2}$

In [79]:
np.array(b)@np.array(b)

147

$b=\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}$, $b^T=[1,2,3]$

$b^T b=[1,2,3]\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}=1^2+2^2+3^2=14$

$b b^T=\begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}[1,2,3]=\begin{bmatrix}1 & 2 & 3 \\
2 & 4 & 6 \\ 
3 & 6 & 9
\end{bmatrix}$

In [48]:
b

[1, 9, 4, 7]

In [49]:
b1=np.array(b)
b2=np.matrix(b).T

In [50]:
print(b2.T*b2) #... (1)
print(b2*b2.T) #... (2)
#print(b2*b2) ... (3)
#print(b2.T*b2.T) ... (4)

[[147]]
[[ 1  9  4  7]
 [ 9 81 36 63]
 [ 4 36 16 28]
 [ 7 63 28 49]]


(1)~(4) 중에 무엇이 맞는 수식인지 따지고 싶지 않다. / 구분 안해도 된다!

In [51]:
b1@b1 #...(1)
b1@b1.T #...(2)
b1.T@b1 #...(3)
b1.T@b1.T #...(4)

147

In [54]:
A=np.array([[1,0],[0,1]])

In [55]:
A

array([[1, 0],
       [0, 1]])

In [56]:
b=np.matrix([200,300]).T

### (3) 인덱싱 (슬라이싱 포함)

In [57]:
A=np.array([[11,12,13,14,15],[21,22,23,24,25],[31,32,33,34,35]])

In [58]:
A

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

**[예제1]** (3,1)에 접근하여 보자!

(방법1)

In [88]:
A[2]

array([31, 32, 33, 34, 35])

In [89]:
A[2][0]

31

(방법2)

In [94]:
A[2,0] # list와의 차이점

31

**[예제2]** 3행에 접근해보자.

(방법1)

In [58]:
A[2]

array([31, 32, 33, 34, 35])

(방법2)

In [59]:
A[2,0:5]

array([31, 32, 33, 34, 35])

(방법3)

In [60]:
A[2,:]

array([31, 32, 33, 34, 35])

**[예제3]** 2열에 접근하여 보자. 

(방법1)

In [95]:
A[:,1]

array([12, 22, 32])

아래가 더 읽기 편하지 않나? 

In [96]:
Amat=np.matrix(A)
Amat[:,1]

matrix([[12],
        [22],
        [32]])

(방법2)

T는 변환이니 기존[]이 행 인덱싱이면 .T[]는 열 인덱싱이다. 

In [59]:
A

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

In [98]:
A.T[2]

array([13, 23, 33])

**[예제4]** 1행중에서 1,3,5열에 접근해보자. 

(방법1)

In [60]:
A[0,[0,2,4]]

array([11, 13, 15])

(방법2)

In [61]:
A[0][[0,2,4]] #가로 안에 [][[]]인 이유는 [][1,2,3]은 여러 수치가 들어가 버린거이기 때문 

array([11, 13, 15])

(방법3)

In [62]:
b=(0,2,4)

In [63]:
A[0][b]

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

(방법4)

In [64]:
A[0,b]

array([11, 13, 15])

**[예제5]** (1,1),(1,2), (2,1),(2,2) 에 접근하자.

(방법1)

In [103]:
A

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

In [70]:
A[0:2,0:2]

array([[11, 12],
       [21, 22]])

(방법2)

In [109]:
a=[0,1]
b=[0,1]
A[a,b]

array([11, 22])

둘다 벡터가 들어갔기 때문에 
A[a[0],b[0]]
A[a[1],b[1]]
가 나와버렸다. 

우리가 원한건
A[0,0], A[0,1]
A[1,0], A[1,1]
이거였는데 

In [72]:
A[a,b]

array([11, 22])

깨달음! 

In [110]:
# A[0,0]
# A[0,1]
# A[1,0]
# A[1,1] 
# * mac : cmd + / 
# * win : ctrl + / 
a=[0,0,1,1]
b=[0,1,0,1]
A[a,b]

array([11, 12, 21, 22])

(방법3)

In [111]:
a=[0,1]
b=[0,1]
A[np.ix_(a,b)]

array([[11, 12],
       [21, 22]])

In [112]:
np.ix_(a,b)

(array([[0],
        [1]]),
 array([[0, 1]]))

**[예제6]**

홀수행, 짝수열을 뽑아보자. 

즉 12,32,14,34 가 뽑혀야함

(방법1)

In [76]:
# A[0,1]
# A[2,1]
# A[0,3]
# A[2,3]

In [77]:
a=[0,2,0,2]
b=[1,1,3,3]
A[a,b]

array([12, 32, 14, 34])

(방법2)

In [78]:
a=[0,2] # 1,3 행 ==> 홀수행
b=[1,3] # 2,4 열 ==> 짝수열 
A[np.ix_(a,b)]

array([[12, 14],
       [32, 34]])

**[예제7]**

2행의 원소중 23보다 작은 원소만? 

(방법1)

In [116]:
#A[1,0] A[1,1]
b=[0,1]
A[1,b]

array([21, 22])

In [117]:
A

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

(방법2)

아래를 관찰해보자.

In [118]:
c=np.random.normal(size=100)
# np.random.normal(size=100)는 표준정규분포에서 100개의 난수를 생성하는 함수

In [119]:
c[c>0]

array([1.39636172, 0.21759459, 2.20842297, 0.69054294, 1.48841495,
       0.37350807, 0.52640008, 1.45483298, 0.38632596, 0.01374408,
       0.6576619 , 0.31130872, 0.07133159, 2.56040194, 1.53486264,
       1.2461994 , 0.40849045, 0.41111438, 0.29771423, 1.27376457,
       0.46588624, 0.03946472, 0.91351687, 0.57605497, 0.08190782,
       0.57229183, 0.13729923, 1.2940632 , 0.02680989, 0.134452  ,
       0.41848333, 0.30913859, 0.79297293, 2.48555845, 0.21021628,
       0.64461624, 0.58458465, 2.82719024, 1.05804052, 0.93083556,
       1.45590051, 0.20098402, 1.3651123 , 0.46191744])

이제 응용해보자. 

In [120]:
a = np.random.normal(size=100)
a[a<0]

array([-1.96216422e-01, -1.63969075e+00, -5.57200617e-01, -5.98140596e-01,
       -9.56191689e-01, -1.58517796e+00, -1.29201728e+00, -7.37077086e-01,
       -2.33123186e-01, -1.07177286e+00, -6.79196712e-01, -8.83515413e-01,
       -4.48204259e-01, -1.40873362e+00, -5.93696131e-01, -2.53701866e+00,
       -3.93436853e-03, -7.33995166e-01, -6.42540255e-01, -1.15707970e+00,
       -4.91534194e-01, -2.21558913e+00, -1.40718929e+00, -3.39383411e-02,
       -1.44271103e+00, -1.74689013e+00, -1.07726532e-01, -1.56507810e+00,
       -3.46305856e-01, -4.74484242e-05, -3.41926843e-01, -1.61676942e-01,
       -1.08415563e-01, -1.10311326e+00, -7.74295482e-01, -1.38483182e+00,
       -8.66506643e-03, -1.62970462e+00, -1.28422308e+00, -1.25530928e+00,
       -9.20065182e-01, -1.57288428e-01, -9.59275454e-02, -2.90031677e+00])

In [66]:
# c -- A[1]
# c>0 -- A[1]<23 
# c[c>0]
A[1][A[1]<23]

array([21, 22])

(방법3)

In [83]:
A[1,:][A[1,:]<23]

array([21, 22])

#### [$\ast$] 인덱싱의 종류 ($\star\star\star$)

1. 기본인덱싱: 인덱스, 슬라이싱을 활용 
   - 예1: `A[1,1]` 
   - 예2: `A[1,0:2]` 
2. 팬시인덱싱(응용인덱싱): 인덱스를 정수배열로 전달, `np.ix_`함수를 활용한 인덱싱, 부울값 인덱싱
    - 예1: `A[0,[0,2,4]]` , 정수배열 인덱싱
    - 예2: `A[np.ix_(a,b)]` , np.ix함수를 활용한 인덱싱 / 각 자리 지정 가능 + 행렬 형식으로 출력 가능
    - 예3: `c[c>0]` , 부울값인덱싱

In [122]:
A

array([[11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

### (4) `numpy`를 배우는 방법

인터넷+자동완성+contextual help 

[$\ast$] 자동완성이 안되면 콘다환경에서 아래를 실행해볼것. 
```
pip install "jedi==0.17.2"
```

In [140]:
a=np.array([1,2,3,2])

In [141]:
a.reshape

<function ndarray.reshape>

In [86]:
a=np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
np.reshape(a, (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])