### if 문 

`-` 예제1

In [6]:
a=11
if a<5: 
    print('a=....1,2,3,4')
elif a>10: 
    print('a=11,12,13,....')
else: 
    print('a=5,6,7,...,10')

a=11,12,13,....


`-` 예제2

In [9]:
a,b=2,3 
if a==b:
    print('a=b')
else: 
    if a<b: 
        print('a<b')
    else:
        print('a>b')

a<b


`-` 예제3

In [21]:
a=2
if a==1: 
    print('a=1')

### for 문 

`-` 예제1

In [22]:
for i in [1,2,3,4]:
    print(i)

1
2
3
4


`-` 예제2

In [23]:
for i in (1,2,3,4):
    print(i)

1
2
3
4


`-` 예제3

In [24]:
for i in '1234':
    print(i)

1
2
3
4


`-` 의문 
```python
for i in ???: 
    print(i)
```
에서 물음표 자리에 올 수 있는 것이 무엇일까? 

`-` 예제4 

In [25]:
a=5 
for i in a:
    print(i)

TypeError: 'int' object is not iterable

`5`라고 출력될 줄 알았는데 아니었다. 

무슨 차이인가? 

아래를 살펴보자. 

`-` 예제5

In [26]:
L=[[1,2,3],[3,4,5]]

In [27]:
for i in L:
    print(i)

[1, 2, 3]
[3, 4, 5]


In [30]:
import pandas as pd
df=pd.DataFrame(L)

In [31]:
for i in df:
    print(i)

0
1
2


In [32]:
import numpy as np 
ndr=np.array(L)

In [33]:
for i in ndr: 
    print(i)

[1 2 3]
[3 4 5]


결과를 어떻게 예상할 수 있을까? 

### for문의 동작원리 

??? 자리에 올 수 있는 것은 dir()하여 `__iter__()`라는 메서드가 있는 object이다. 

이러한 오브젝트를 iterable한 오브젝트다. 

In [34]:
a=1

In [35]:
dir(a)

['__abs__',
 '__add__',
 '__and__',
 '__bool__',
 '__ceil__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floor__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__le__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__trunc__',
 '__xor__',
 'as_integer_ratio',
 'bit_length',
 'conjugate',
 'denominator',
 'from_bytes',
 'imag',
 'numerator',
 'real',
 'to_bytes']

예상대로 int클래스의 인스턴스는 `__iter__()`가 없다. 

`-` 위에서 정의한 L, df, ndr 는 모두 `__iter__()` 함수가 있다. 따라서 iterable한 오브젝트이다. 

iterable한 오브젝트는 iterator로 만들 수 있는 특징이 있다. 

iterable한 오브젝트를 어떻게 iterator로 만드는가? 

In [50]:
### 방법1
dfiter1=df.__iter__()

In [53]:
### 방법2
dfiter2=iter(df)

In [55]:
dfiter1?

Type:        generator
String form: <generator object RangeIndex.__iter__ at 0x7f5a202c5890>
Docstring:   <no docstring>


`-` dfiter1은 generator라는 클래스에서 만들어진 인스턴스 오브젝트이다. 

In [ ]:
`-` dfiter1

In [44]:
dir(dfiter1)

['__class__',
 '__del__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__name__',
 '__ne__',
 '__new__',
 '__next__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'close',
 'gi_code',
 'gi_frame',
 'gi_running',
 'gi_yieldfrom',
 'send',
 'throw']

In [59]:
dfiter1.__next__()

StopIteration: 

`–` for 문의 작동원리 

```python
for i in L:
    print(i)
```

(1) iter함수를 사용해서 L을 iterator로 만든다. 

(2) iterator에서 `.__next__()`함수를 호출하고 결과를 i에 저장한뒤에 for문 블락안에 있는 내용(들여쓰기 된 내용)을 실행한다. 

(3) StopIteration 에러가 발생하면 for 문을 멈춘다. 

In [62]:
Liter=iter(L)

In [69]:
Liter.__next__()

StopIteration: 

In [80]:
ndriter=iter(ndr)

In [82]:
print(ndriter.__next__())

[3 4 5]


#### range()

`-` for문의 정석은 아래와 같이 range()를 사용하는 것이다. 

In [83]:
for i in range(5):
    print(i)

0
1
2
3
4


`-` `range(5)`의 정체는 그냥 iterable object이다. 

In [85]:
a=range(5)

`-` 그래서 언제든지 iterator로 바꿀 수 있다. 

In [88]:
aiter=iter(a)

In [96]:
aiter.__next__()

StopIteration: 

#### 이터레이터의 개념은 디버깅에 응용가능 

In [97]:
for i in zip([1,2,3],'abc'):
    print(i)

(1, 'a')
(2, 'b')
(3, 'c')


In [98]:
zip([1,2,3],'abc')

어차피 `for i in ????:` ????의 자리는 iterable object 자리이다. 

In [99]:
z=zip([1,2,3],'abc')

In [100]:
dir(z)

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__next__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__']

`-` `__next__()`함수가 있음 $\to$ z자체가 iterator였다. (iterable object 이면서)

In [108]:
z.__next__()

StopIteration: 

`-` ???? 자리에 iterator 자체가와도 무방할것 같다. 

`-` 확인

In [107]:
L=iter([1,2,3,4])
for i in L:
    print(i)

1
2
3
4


역시 가능했다.. 