### 강의영상 

> youtube: https://youtube.com/playlist?list=PLQqh36zP38-zaw-dCrB3YG7QJUInlJ0P7

`-` (1/5) 넘파이공부 1단계: 선언, 기본연산 브로드캐스팅, 기타수학연산지원 

`-` (2/5) 넘파이공부 2단계: 인덱싱1차원, 인덱싱2차원

`-` (3/5) 넘파이공부 2단계: 1차원 배열의 선언 

`-` (4/5) 넘파이공부 2단계: reshape 

`-` (5/5) 넘파이공부 2단계: 2차원 배열의 선언, 랜덤으로 배열 생성, 행렬관련기능 

### import 

In [1]:
import numpy as np

### 넘파이 공부 1단계 

#### 선언 

In [2]:
a=np.array([1,2,3]) # list를 만들고 ndarray화 시킴 
l=[1,2,3]

#### 기본연산 브로드캐스팅 

In [3]:
a+1 ## [1,2,3] + 1 = [2,3,4]

array([2, 3, 4])

In [4]:
l+1

TypeError: can only concatenate list (not "int") to list

In [ ]:
a*2

In [5]:
l*2

[1, 2, 3, 1, 2, 3]

In [6]:
a/2

array([0.5, 1. , 1.5])

In [7]:
l/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [8]:
a**2

array([1, 4, 9])

In [9]:
l**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [10]:
a%2 # %2 = 2로 나눈 나머지를 리턴 a=[1,2,3] 

array([1, 0, 1])

In [11]:
l%2

TypeError: unsupported operand type(s) for %: 'list' and 'int'

#### 기타수학연산지원 

In [12]:
np.sqrt(a), np.sqrt(l)

(array([1.        , 1.41421356, 1.73205081]),
 array([1.        , 1.41421356, 1.73205081]))

In [13]:
np.log(a), np.log(l)

(array([0.        , 0.69314718, 1.09861229]),
 array([0.        , 0.69314718, 1.09861229]))

In [14]:
np.exp(a), np.exp(l)

(array([ 2.71828183,  7.3890561 , 20.08553692]),
 array([ 2.71828183,  7.3890561 , 20.08553692]))

In [15]:
np.sin(a), np.sin(l)

(array([0.84147098, 0.90929743, 0.14112001]),
 array([0.84147098, 0.90929743, 0.14112001]))

### 넘파이 공부 2단계 

#### 인덱싱 1차원 

`-` 선언 

In [16]:
l=[11,22,33,44,55,66] 
a=np.array(l) 

`-` 인덱스로 접근 

In [17]:
l[0],l[1],l[2],l[3],l[-2],l[-1]

(11, 22, 33, 44, 55, 66)

In [18]:
a[0],a[1],a[2],a[3],a[-2],a[-1]

(11, 22, 33, 44, 55, 66)

`-` `:` 이용 (슬라이싱)

In [19]:
l[2:4] # index 2에서 시작, index 4는 포함하지 않음 

[33, 44]

In [20]:
a[2:4] 

array([33, 44])

`-` 정수배열에 의한 인덱싱 

In [32]:
a

array([11, 22, 33, 44, 55, 66])

In [33]:
a[[0,2,4]] # index=0, index=2, index=4 에 해당하는 원소를 뽑고 싶다 

array([11, 33, 55])

In [34]:
l[[0,2,4]] # 리스트는 불가능 

TypeError: list indices must be integers or slices, not list

`-` 부울값에 의한 인덱싱 

In [35]:
a

array([11, 22, 33, 44, 55, 66])

In [36]:
a[[True,False,True,False,True,False]] 

array([11, 33, 55])

응용하면? 

In [37]:
a < 33 

array([ True,  True, False, False, False, False])

In [38]:
a[a<33]

array([11, 22])

리스트는 불가능 

In [39]:
l<33 # 여기에서부터 불가능 

TypeError: '<' not supported between instances of 'list' and 'int'

In [40]:
l[[True,False,True,False,True,False]] # 이것도 불가능 

TypeError: list indices must be integers or slices, not list

#### 인덱싱 2차원 

`-` 중첩리스트와 2차원 np.array 선언 

In [41]:
A = [[1,2,3,4],[-1,-2,-3,-4],[5,6,7,8],[-5,-6,-7,-8]]
A2 = np.array(A)

In [42]:
A2

array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4],
       [ 5,  6,  7,  8],
       [-5, -6, -7, -8]])

In [43]:
A

[[1, 2, 3, 4], [-1, -2, -3, -4], [5, 6, 7, 8], [-5, -6, -7, -8]]

`-` A의 원소 인덱싱 

In [44]:
A[0][0] # (1,1)의 원소 

1

In [45]:
A[1][2] # (2,3)의 원소 

-3

In [46]:
A[-1][0] # (4,1)의 원소 

-5

`-` A2의 원소 인덱싱 

In [47]:
A2[0][0] # (1,1)의 원소 

1

In [48]:
A2[1][2] # (2,3)의 원소 

-3

In [49]:
A2[-1][0] # (4,1)의 원소 

-5

`-` A2에서만 되는 기술 (넘파이에서 제시하는 신기술, R에서는 기본적으로 쓰던것, 이중list는 불가능) 

In [50]:
A2[0,0] # (1,1)의 원소 

1

In [51]:
A2[1,2] # (2,3)의 원소 

-3

In [52]:
A2[-1,0] # (4,1)의 원소 

-5

`-` 정수배열에 의한 인덱싱 & 슬라이싱!

In [53]:
A2

array([[ 1,  2,  3,  4],
       [-1, -2, -3, -4],
       [ 5,  6,  7,  8],
       [-5, -6, -7, -8]])

In [54]:
A2[0,0:2] # 1행1열, 1행2열 

array([1, 2])

In [55]:
A2[0,:] # 1행 

array([1, 2, 3, 4])

In [56]:
A2[0] # 1행

array([1, 2, 3, 4])

In [57]:
A2[[0,2],:] # 1행, 3행 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
A2[[0,2]] # 1행, 3행 

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [67]:
A2[:,0] # 1열 / 배열 형태로 쭉 나왔다. 

array([ 1, -1,  5, -5])

In [68]:
A2[:,[0]] # 1열 / 2차원 형태를 유지하며 출력

array([[ 1],
       [-1],
       [ 5],
       [-5]])

In [69]:
A2[:,[0,2]] # 1열, 3열

array([[ 1,  3],
       [-1, -3],
       [ 5,  7],
       [-5, -7]])

In [70]:
A2[0:2,[0,2]] # 1행~2행 //  1열,3열 

array([[ 1,  3],
       [-1, -3]])

#### 1차원 배열의 선언 

`-` 리스트나 튜플을 선언하고 형변환 

In [71]:
np.array((1,2,3)) # 튜플->넘파이어레이 

array([1, 2, 3])

In [72]:
np.array([1,2,3]) # 리스트 ->넘파이어레이 

array([1, 2, 3])

`-` range()를 이용해서 선언하고 형변환 

In [73]:
np.array(range(10)) # range(10) -> 넘파이어레이 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`-` np.zeros, np.ones

In [76]:
np.zeros(3) # dtype = int - 정수형

array([0., 0., 0.])

In [77]:
np.ones(4)

array([1., 1., 1., 1.])

`-` np.linspace 

In [81]:
np.linspace(0,1,12) # 0에서 시작하고 1에서 끝남 (양끝점 모두 포함) 간격이 같음

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

In [82]:
len(np.linspace(0,1,12)) # 길이는 12

12

`-` np.arange

In [83]:
np.arange(5) # np.array(range(5))

array([0, 1, 2, 3, 4])

In [84]:
np.arange(1,6) # np.array(range(1,6))

array([1, 2, 3, 4, 5])

#### reshape 

`-` reshape: ndarray의 특수한 기능 

In [89]:
a=np.array([11,22,33,44,55,66])
a ## 길이가 6인 벡터 

array([11, 22, 33, 44, 55, 66])

In [90]:
a.reshape(2,3) ## (2,3) matrix 라고 생각해도 무방 

array([[11, 22, 33],
       [44, 55, 66]])

note: reshape은 a자체를 변화시키는것은 아님 

In [95]:
a # a는 그대로 있음 

array([11, 22, 33, 44, 55, 66])

In [96]:
b= a.reshape(2,3) # a를 reshape한 결과를 b에 저장 
b

array([[11, 22, 33],
       [44, 55, 66]])

In [97]:
a # a는 여전히 그대로 있음

array([11, 22, 33, 44, 55, 66])

`-` 다시 b를 a처럼 바꾸고 싶다 

In [98]:
b

array([[11, 22, 33],
       [44, 55, 66]])

In [99]:
b.reshape(6) # b는 (2,3) matrix , 그런데 이것을 길이가 6인 벡터로 만들고 싶다. 

array([11, 22, 33, 44, 55, 66])

`-` reshape with -1 

In [103]:
a=np.arange(24) # np.array(range(24))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [116]:
a.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [105]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [106]:
a.reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [107]:
a.reshape(5,-1)

ValueError: cannot reshape array of size 24 into shape (5,newaxis)

In [109]:
a.reshape(6,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [110]:
a.reshape(7,-1)

ValueError: cannot reshape array of size 24 into shape (7,newaxis)

In [111]:
a.reshape(8,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [112]:
a.reshape(12,-1)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [113]:
b= a.reshape(12,-1)
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [117]:
b.reshape(-1) # b를 다시 길이가 24인 벡터로!

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

#### 2차원 배열의 선언 

In [118]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [119]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [121]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [122]:
np.diag([1,2,3,-1]) # 2차원 배열까지만 가능함. 

array([[ 1,  0,  0,  0],
       [ 0,  2,  0,  0],
       [ 0,  0,  3,  0],
       [ 0,  0,  0, -1]])

#### 랜덤으로 배열 생성 

In [124]:
np.random.randn(10) # 표쥰정규분포에서 10개를 뽑음 

array([ 0.19370735, -0.07854209,  0.47217415, -0.09728545, -0.47613894,
       -0.29424211,  0.65691114,  1.20060197, -0.61833351,  1.5681596 ])

In [125]:
np.random.rand(10) # 0~1사이에서 10개를 뽑음

array([0.07810505, 0.24026997, 0.39514741, 0.76085858, 0.78302376,
       0.6450981 , 0.91694227, 0.83103042, 0.12395802, 0.04433416])

In [126]:
np.random.randn(4).reshape(2,2) # 표준정규분포에서 4개를 뽑고 (2,2) ndarray로 형태변환 

array([[-0.1841771 ,  0.40172971],
       [-0.12214722,  0.76196843]])

In [127]:
np.random.rand(4).reshape(2,2) # 0~1 4개를 뽑고 (2,2) ndarray로 형태변환 

array([[4.40071093e-05, 5.34088558e-01],
       [6.65064360e-01, 5.35544620e-01]])

#### 행렬관련기능

In [141]:
A=np.arange(4).reshape(2,2) 
A

array([[0, 1],
       [2, 3]])

In [142]:
A.T # .T는 전치행렬을 구해줌 (행렬의 행과 열을 바꿈)

array([[0, 2],
       [1, 3]])

In [143]:
np.linalg.inv(A) # np.linalg.inv는 역행렬을 구해주는 함수 

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [144]:
A @ np.linalg.inv(A) # @는 행렬곱을 수행 

array([[1., 0.],
       [0., 1.]])