### 강의영상 


> youtube: https://youtube.com/playlist?list=PLQqh36zP38-yPErl_8ayWONJ_f-XH6MuR

`-` (1/3) rand, randn

`-` (2/3) randint 

`-` (3/3) choice, 통계분포, np.where/np.argwhere, 인덱싱고급, np.ix_ 

### import 

In [3]:
import numpy as np

### numpy공부 5단계: 랜덤모듈 

#### np.random.rand()

`-` 0~1사이에서 10개의 난수 생성 

In [4]:
np.random.rand(10)

array([0.48606112, 0.84983039, 0.71049221, 0.30104962, 0.63573744,
       0.13789887, 0.20609986, 0.9043582 , 0.90579688, 0.31072028])

`-` 0~2사이에서 10개의 난수 생성 

In [5]:
np.random.rand(10)*2 

array([0.14198594, 1.61970572, 1.75760371, 1.98876074, 0.81178648,
       1.91701101, 1.57718276, 1.68038849, 0.97290079, 0.93781008])

`-` 1~2사이에서 10개의 난수 생성 

In [6]:
np.random.rand(10)+1

array([1.89413482, 1.4118153 , 1.20684537, 1.72636907, 1.70118081,
       1.04705709, 1.01872508, 1.64570942, 1.74970791, 1.98345281])

`-` 1~3사이에서 10개의 난수 생성 

In [7]:
np.random.rand(10)*2+1 # 1~3

array([1.54242598, 2.35152133, 2.25873873, 2.97290175, 2.54679417,
       1.61525529, 1.18244899, 1.02780492, 2.33479968, 1.29977913])

#### np.random.randn()

`-` N(0,1)에서 10개 추출 

In [8]:
np.random.randn(10) # 표준정규분포에서 10개의 샘플 추출 

array([ 0.5640164 ,  0.69704413,  0.67137209, -0.21875175,  0.04283005,
        0.86270498, -1.0946091 , -2.41075761, -0.93020341,  0.11504301])

`-` N(1,1)에서 10개 추출 

In [9]:
np.random.randn(10)+1 

array([ 0.73870169, -0.39795093,  0.75555929,  1.49549289,  0.57081322,
        0.03462221, -0.29127835, -0.1740883 ,  0.57859526, -1.79503048])

`-` N(0,4)에서 10개 추출 (평균이 0이고 분산이 4인 분포)

In [10]:
np.random.randn(10)*2

array([-1.00082952, -5.15413772,  0.22735941, -0.62995336, -4.56138329,
        0.35738251,  0.33185927, -0.80619047, -3.69441923,  2.09722405])

`-` N(3,4)에서 10개 추출 

In [11]:
np.random.randn(10)*2+3 

array([1.87403902, 0.24298405, 1.76776333, 2.86724453, 4.25141232,
       5.72789246, 4.21994149, 5.10489463, 5.58219895, 1.1503181 ])

#### np.random.randint() 

`-` [0,7)의 범위에서 하나의 정수를 랜덤으로 생성 

In [12]:
np.random.randint(7) # [0,7)의 범위에서 하나의 정수 생성 

0

`-` [0,7)의 범위에서 20개의 정수를 랜덤으로 생성 

In [16]:
np.random.randint(7,size=(20,)) # [0,7)의 범위에서 20개의 정수 생성 

array([2, 2, 5, 0, 4, 2, 1, 4, 1, 2, 0, 6, 6, 6, 1, 3, 2, 1, 4, 1])

`-` [0,7)의 범위에서 (2,2) shape 으로 정수를 랜덤으로 생성

In [17]:
np.random.randint(7,size=(2,2)) # [0,7)의 범위에서 (2,2) shape의 정수 생성 

array([[6, 3],
       [6, 3]])

`-` 위와 같은 코드를 아래와 같이 구현가능 

In [18]:
np.random.randint(low=7,size=(5,5)) # [0,7)의 범위에서 (5,5) shape의 정수 생성 

array([[3, 3, 0, 6, 5],
       [0, 6, 4, 1, 2],
       [2, 1, 1, 4, 5],
       [2, 1, 1, 6, 4],
       [6, 1, 4, 1, 5]])

`-` [10,20) 의 범위에서 (5,5) shape 정수를 랜덤으로 생성 

In [19]:
np.random.randint(low=10,high=20,size=(5,5)) # [10,20)의 범위에서 (5,5)shape의 정수생성 

array([[15, 16, 18, 17, 17],
       [19, 14, 18, 16, 15],
       [17, 11, 14, 11, 19],
       [14, 11, 14, 12, 14],
       [10, 13, 13, 17, 12]])

`-` 의문: `np.random.randint(low=7,size=(5,5))` 가 좀 이상하다. 사실 `np.random.randint(high=7,size=(5,5))`가 되어야 맞지 않는가? 

-> 저도 그렇게 생각하긴 하는데요, 구현이 이렇게 되어있습니다. 도움말 확인!
```
Return random integers from the "discrete uniform" distribution of the specified dtype in the "half-open" interval [`low`, `high`). If `high` is None (the default), then results are from [0, `low`).
```

#### np.random.choice()

`-` ver1 

In [20]:
np.random.choice(5,20) # [0,5)에서 20개를 뽑음, 중복허용 

array([0, 4, 3, 0, 2, 3, 2, 2, 2, 4, 0, 0, 3, 4, 1, 0, 1, 1, 1, 1])

- 이것은 np.random.randint(5,size=(20,)) 와 같은 코드임 

`-` ver2 

In [21]:
np.random.choice([0,1,2,3],20) # [0,1,2,3]에서 20개를 뽑음, 중복허용

array([0, 2, 0, 2, 3, 2, 3, 1, 1, 3, 3, 3, 0, 1, 0, 3, 3, 1, 2, 1])

In [22]:
np.random.choice(["apple","orange","banana"],20)

array(['banana', 'apple', 'apple', 'orange', 'banana', 'apple', 'banana',
       'apple', 'apple', 'banana', 'orange', 'orange', 'apple', 'apple',
       'apple', 'banana', 'apple', 'orange', 'banana', 'orange'],
      dtype='<U6')

In [23]:
np.random.choice(["apple","orange","banana"],2,replace=False) # 중복허용 X 

array(['orange', 'apple'], dtype='<U6')

#### 통계분포 

In [24]:
np.random.binomial(n=10,p=0.2,size=(5,)) # X1, ..., X5 ~ B(10,0.2) 

array([3, 0, 2, 3, 4])

In [25]:
np.random.normal(loc=10,scale=2,size=(5,)) # X1, ..., X5 ~ N(10,4) 

array([11.77018357,  7.07424301, 11.42087349, 10.70109446,  7.89221899])

- `np.radom.randn(5)*2 + 10 `와 같은코드

In [26]:
np.random.uniform(low=2,high=4,size=(5,)) # X1, ..., X5 ~ U(2,4) 

array([2.07791384, 3.93809117, 2.18416963, 2.7858042 , 3.19308168])

- `np.random.rand(5)*2+2 `와 같은 코드 

In [27]:
np.random.poisson(lam=5,size=(5,)) # X1,...,X5 ~ Poi(5) 

array([3, 6, 8, 4, 1])

### numpy공부 6단계: 기타 유용한 기본기능들 

#### np.where, np.argwhere 

np array의 조건에 따른 위치를 파악하기 위한 함수. 

`-` 1차원 

In [30]:
a=np.array([0,0,0,1,0])
a

array([0, 0, 0, 1, 0])

In [31]:
np.where(a==1) # 조건 a==1을 만족하는 인덱스를 출력하라!

(array([3]),)

In [32]:
np.argwhere(a==1)

array([[3]])

`-` 2차원 

In [33]:
np.random.seed(43052)
a=np.random.randn(12).reshape(3,4)
a

array([[ 0.38342049,  1.0841745 ,  1.14277825,  0.30789368],
       [ 0.23778744,  0.35595116, -1.66307542, -1.38277318],
       [-1.92684484, -1.4862163 ,  0.00692519, -0.03488725]])

In [34]:
np.where(a<0) # 조건을 만족하는 인덱스가 (1,2), (1,3), (2,0), (2,1), (2,3) 이라는 의미

(array([1, 1, 2, 2, 2]), array([2, 3, 0, 1, 3]))

In [35]:
np.argwhere(a<0) # 조건을 만족하는 인덱스가 (1,2), (1,3), (2,0), (2,1), (2,3) 이라는 의미

array([[1, 2],
       [1, 3],
       [2, 0],
       [2, 1],
       [2, 3]])

In [36]:
a[np.where(a<0)] # 조건을 만족하는 인덱스가 모두 출력 => 1차원 array로 출력 

array([-1.66307542, -1.38277318, -1.92684484, -1.4862163 , -0.03488725])

In [37]:
a[np.argwhere(a<0)] # 출력불가능

IndexError: index 3 is out of bounds for axis 0 with size 3

In [38]:
a[np.argwhere(a<0)[0][0],np.argwhere(a<0)[0][1]] # 어거지로 출력할수는 있음 

-1.6630754187023522

`-` np.where의 특수기능 

In [39]:
np.random.seed(43052) 
a=np.random.randn(12).reshape(3,4) 
a

array([[ 0.38342049,  1.0841745 ,  1.14277825,  0.30789368],
       [ 0.23778744,  0.35595116, -1.66307542, -1.38277318],
       [-1.92684484, -1.4862163 ,  0.00692519, -0.03488725]])

In [40]:
np.where(a<0,0,a) # a<0을 체크 => 조건에 맞으면 0 => 조건에 안맞으면 a 

array([[0.38342049, 1.0841745 , 1.14277825, 0.30789368],
       [0.23778744, 0.35595116, 0.        , 0.        ],
       [0.        , 0.        , 0.00692519, 0.        ]])

In [42]:
np.where(a<0,0,1) # a<0을 체크 => 조건에 맞으면 0 => 조건에 안맞으면 1

array([[1, 1, 1, 1],
       [1, 1, 0, 0],
       [0, 0, 1, 0]])

`-` 요약 
- np.where: 인덱스의 좌표를 읽는 가독성은 떨어짐. 그런데 조건에 맞는 원소를 출력하거나 처리하는 (특수기능) 목적으로는 좋은 함수  
- np.argwhere: 인덱스의 좌표를 읽는 가독성은 좋은 편임. 그런데 조건에 맞는 원소를 출력하거나 처리하는 기능은 떨어짐

#### 인덱싱고급 

`-` 원래 a는 2d array

In [43]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

`-` 경우1: 인덱싱 결과가 1d array로 나올수 있음 

In [45]:
a[0,:] # 인덱싱의 결과 축의 갯수가 바뀐다! 2d array -> 1d array

array([0, 1, 2, 3])

`-` 경우2: 물론 인덱싱 결과가 2d array로 나올 수도 있음 

In [47]:
a[[0,1],:] # 이것은 축의 숫자가 유지된다. 2d array -> 2d array 

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

`-` 경우1의 상황에서도 축의 갯수를 유지하면서 인덱싱하려면? 

In [48]:
a[[0],:] # 이번에는 인덱싱의 결과 축의 갯수가 유지된다! 2d array -> 2d array

array([[0, 1, 2, 3]])

In [49]:
a[:,[0]] 

array([[0],
       [4],
       [8]])

`-` 미묘한 차이를 이해할것 

In [52]:
a[0,:], a[[0],:]

(array([0, 1, 2, 3]), array([[0, 1, 2, 3]]))

In [53]:
a[:,0], a[:,[0]]

(array([0, 4, 8]),
 array([[0],
        [4],
        [8]]))

#### np.ix_ 

`-` 아래의 인덱싱을 비교하자. 

In [56]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
a[0:2,0:2]

array([[0, 1],
       [4, 5]])

In [58]:
a[[0,1],0:2]

array([[0, 1],
       [4, 5]])

In [59]:
a[0:2,[0,1]]

array([[0, 1],
       [4, 5]])

`-` 언뜻 생각하면 위의 결과와 `a[[0,1],[0,1]]`는 결과가 동일할 것 같다.  

In [60]:
a[[0,1],[0,1]]

array([0, 5])

- 실제로는 [a[0,0],a[1,1]]이 array로 나옴 

`-` 사실 np.where에서 이미 관찰하였음 

In [61]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
np.where(a % 5 ==0)

(array([0, 1, 2]), array([0, 1, 2]))

In [63]:
a[np.where(a % 5 ==0)]

array([ 0,  5, 10])

In [64]:
a[[0, 1, 2],[0, 1, 2]]

array([ 0,  5, 10])

`-` a[[0,1],[0,1]]이 a[0:2,0:2]를 의미하게 하려면 아래와 같이 하면 된다. 

In [65]:
a[np.ix_([0,1],[0,1])] # 유용해보이지만 생각보다 잘 쓰이는건 아님 

array([[0, 1],
       [4, 5]])

### 숙제

In [67]:
np.random.seed(10)
np.random.uniform(low=1.3,high=1.7,size=(10,))

array([1.60852826, 1.30830078, 1.55345929, 1.59952155, 1.4994028 ,
       1.38991866, 1.37922515, 1.60421228, 1.36764433, 1.33533593])

위와 같은코드를 np.random.rand()를 이용하여 구현하라. 

In [77]:
np.random.seed(10)
np.random.rand(10)*0.4+1.3 # 1~2

array([1.60852826, 1.30830078, 1.55345929, 1.59952155, 1.4994028 ,
       1.38991866, 1.37922515, 1.60421228, 1.36764433, 1.33533593])